-- Primera fase de identidad, carrito normalizado y eventos.
-- Revisar y respaldar antes de ejecutar manualmente. Este archivo no migra tablas historicas.

CREATE TABLE `stj_visitantes` (
  `vis_id` BIGINT NOT NULL AUTO_INCREMENT,
  `vis_uuid` CHAR(36) NOT NULL,
  `vis_origen` VARCHAR(20) NOT NULL DEFAULT 'WEB',
  `vis_pais_id` BIGINT NULL,
  `vis_primera_visita` DATETIME(6) NOT NULL,
  `vis_ultima_visita` DATETIME(6) NOT NULL,
  `vis_expira_en` DATETIME(6) NOT NULL,
  `vis_creado_en` DATETIME(6) NOT NULL,
  `vis_actualizado_en` DATETIME(6) NOT NULL,
  PRIMARY KEY (`vis_id`),
  UNIQUE KEY `stj_visitantes_vis_uuid_unique` (`vis_uuid`),
  KEY `stj_visitantes_vis_pais_id_vis_ultima_visita_index` (`vis_pais_id`, `vis_ultima_visita`),
  KEY `stj_visitantes_vis_expira_en_index` (`vis_expira_en`),
  CONSTRAINT `stj_visitantes_vis_pais_id_foreign` FOREIGN KEY (`vis_pais_id`) REFERENCES `stj_paises` (`pai_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stj_carritos` (
  `car_id` BIGINT NOT NULL AUTO_INCREMENT,
  `car_uuid` CHAR(36) NOT NULL,
  `car_visitante_id` BIGINT NOT NULL,
  `car_usu_id` BIGINT NULL,
  `car_pais_id` BIGINT NOT NULL,
  `car_pedido_id` BIGINT NULL,
  `car_tipo` VARCHAR(20) NOT NULL,
  `car_estado` VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  `car_origen` VARCHAR(20) NOT NULL DEFAULT 'WEB',
  `car_moneda` CHAR(3) NOT NULL,
  `car_version` INT UNSIGNED NOT NULL DEFAULT 1,
  `car_ultima_actividad_en` DATETIME(6) NOT NULL,
  `car_expira_en` DATETIME(6) NOT NULL,
  `car_checkout_en` DATETIME(6) NULL,
  `car_convertido_en` DATETIME(6) NULL,
  `car_creado_en` DATETIME(6) NOT NULL,
  `car_actualizado_en` DATETIME(6) NOT NULL,
  PRIMARY KEY (`car_id`),
  UNIQUE KEY `stj_carritos_car_uuid_unique` (`car_uuid`),
  KEY `stj_carritos_car_visitante_id_car_estado_index` (`car_visitante_id`, `car_estado`),
  KEY `stj_carritos_car_usu_id_car_estado_index` (`car_usu_id`, `car_estado`),
  KEY `stj_carritos_car_estado_car_expira_en_index` (`car_estado`, `car_expira_en`),
  CONSTRAINT `stj_carritos_car_visitante_id_foreign` FOREIGN KEY (`car_visitante_id`) REFERENCES `stj_visitantes` (`vis_id`),
  CONSTRAINT `stj_carritos_car_usu_id_foreign` FOREIGN KEY (`car_usu_id`) REFERENCES `stj_usuarios` (`usu_id`),
  CONSTRAINT `stj_carritos_car_pais_id_foreign` FOREIGN KEY (`car_pais_id`) REFERENCES `stj_paises` (`pai_id`),
  CONSTRAINT `stj_carritos_car_pedido_id_foreign` FOREIGN KEY (`car_pedido_id`) REFERENCES `stj_pedidos` (`ped_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stj_carrito_detalles` (
  `cad_id` BIGINT NOT NULL AUTO_INCREMENT,
  `cad_carrito_id` BIGINT NOT NULL,
  `cad_producto_id` BIGINT NOT NULL,
  `cad_promocion_id` BIGINT NULL,
  `cad_talla` VARCHAR(10) NOT NULL,
  `cad_ref` VARCHAR(50) NULL,
  `cad_cantidad` INT UNSIGNED NOT NULL,
  `cad_precio_unitario` DECIMAL(12,2) NOT NULL,
  `cad_descuento_unitario` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `cad_precio_final_unitario` DECIMAL(12,2) NOT NULL,
  `cad_promocion` VARCHAR(150) NULL,
  `cad_seleccionado` TINYINT(1) NOT NULL DEFAULT 1,
  `cad_creado_en` DATETIME(6) NOT NULL,
  `cad_actualizado_en` DATETIME(6) NOT NULL,
  PRIMARY KEY (`cad_id`),
  KEY `stj_carrito_detalles_cad_carrito_id_cad_producto_id_index` (`cad_carrito_id`, `cad_producto_id`),
  KEY `stj_carrito_detalles_cad_promocion_id_index` (`cad_promocion_id`),
  CONSTRAINT `stj_carrito_detalles_cad_carrito_id_foreign` FOREIGN KEY (`cad_carrito_id`) REFERENCES `stj_carritos` (`car_id`),
  CONSTRAINT `stj_carrito_detalles_cad_producto_id_foreign` FOREIGN KEY (`cad_producto_id`) REFERENCES `stj_productos` (`pro_id`),
  CONSTRAINT `stj_carrito_detalles_cad_promocion_id_foreign` FOREIGN KEY (`cad_promocion_id`) REFERENCES `stj_promociones` (`prm_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stj_carrito_auditoria` (
  `cau_id` BIGINT NOT NULL AUTO_INCREMENT,
  `cau_carrito_id` BIGINT NOT NULL,
  `cau_detalle_id` BIGINT NULL,
  `cau_visitante_id` BIGINT NULL,
  `cau_usu_id` BIGINT NULL,
  `cau_accion` VARCHAR(32) NOT NULL,
  `cau_origen` VARCHAR(20) NOT NULL DEFAULT 'WEB',
  `cau_cantidad_anterior` INT UNSIGNED NULL,
  `cau_cantidad_nueva` INT UNSIGNED NULL,
  `cau_datos_anteriores` JSON NULL,
  `cau_datos_nuevos` JSON NULL,
  `cau_ocurrido_en` DATETIME(6) NOT NULL,
  PRIMARY KEY (`cau_id`),
  KEY `stj_carrito_auditoria_cau_carrito_id_cau_ocurrido_en_index` (`cau_carrito_id`, `cau_ocurrido_en`),
  KEY `stj_carrito_auditoria_cau_usu_id_cau_ocurrido_en_index` (`cau_usu_id`, `cau_ocurrido_en`),
  CONSTRAINT `stj_carrito_auditoria_cau_carrito_id_foreign` FOREIGN KEY (`cau_carrito_id`) REFERENCES `stj_carritos` (`car_id`),
  CONSTRAINT `stj_carrito_auditoria_cau_detalle_id_foreign` FOREIGN KEY (`cau_detalle_id`) REFERENCES `stj_carrito_detalles` (`cad_id`),
  CONSTRAINT `stj_carrito_auditoria_cau_visitante_id_foreign` FOREIGN KEY (`cau_visitante_id`) REFERENCES `stj_visitantes` (`vis_id`),
  CONSTRAINT `stj_carrito_auditoria_cau_usu_id_foreign` FOREIGN KEY (`cau_usu_id`) REFERENCES `stj_usuarios` (`usu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stj_cliente_eventos` (
  `cev_id` BIGINT NOT NULL AUTO_INCREMENT,
  `cev_event_uuid` CHAR(36) NOT NULL,
  `cev_visitante_id` BIGINT NOT NULL,
  `cev_usu_id` BIGINT NULL,
  `cev_pais_id` BIGINT NULL,
  `cev_producto_id` BIGINT NULL,
  `cev_pedido_id` BIGINT NULL,
  `cev_carrito_id` BIGINT NULL,
  `cev_tipo` VARCHAR(32) NOT NULL,
  `cev_cantidad` INT UNSIGNED NULL,
  `cev_valor` DECIMAL(12,2) NULL,
  `cev_moneda` CHAR(3) NULL,
  `cev_origen` VARCHAR(20) NOT NULL DEFAULT 'WEB',
  `cev_ocurrido_en` DATETIME(6) NOT NULL,
  `cev_recibido_en` DATETIME(6) NOT NULL,
  `cev_metadata` JSON NULL,
  PRIMARY KEY (`cev_id`),
  UNIQUE KEY `uq_cev_event_uuid` (`cev_event_uuid`),
  KEY `idx_cev_visitante_fecha` (`cev_visitante_id`, `cev_ocurrido_en`),
  KEY `idx_cev_usuario_fecha` (`cev_usu_id`, `cev_ocurrido_en`),
  KEY `idx_cev_producto_tipo_fecha` (`cev_producto_id`, `cev_tipo`, `cev_ocurrido_en`),
  KEY `idx_cev_pais_tipo_fecha` (`cev_pais_id`, `cev_tipo`, `cev_ocurrido_en`),
  KEY `idx_cev_pedido` (`cev_pedido_id`),
  KEY `idx_cev_carrito` (`cev_carrito_id`),
  CONSTRAINT `fk_cev_visitante` FOREIGN KEY (`cev_visitante_id`) REFERENCES `stj_visitantes` (`vis_id`),
  CONSTRAINT `fk_cev_usuario` FOREIGN KEY (`cev_usu_id`) REFERENCES `stj_usuarios` (`usu_id`),
  CONSTRAINT `fk_cev_pais` FOREIGN KEY (`cev_pais_id`) REFERENCES `stj_paises` (`pai_id`),
  CONSTRAINT `fk_cev_producto` FOREIGN KEY (`cev_producto_id`) REFERENCES `stj_productos` (`pro_id`),
  CONSTRAINT `fk_cev_pedido` FOREIGN KEY (`cev_pedido_id`) REFERENCES `stj_pedidos` (`ped_id`),
  CONSTRAINT `fk_cev_carrito` FOREIGN KEY (`cev_carrito_id`) REFERENCES `stj_carritos` (`car_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
