-- Estructura del modulo Push Web automatizado.
-- No modifica stj_notificaciones_push, stj_notificaciones_push_envios ni stj_tokens.
-- Ejecutar manualmente y en el orden indicado despues de revisar el esquema.

CREATE TABLE `stj_push_suscripciones` (
  `psu_id` BIGINT NOT NULL AUTO_INCREMENT,
  `psu_visitante_id` BIGINT NULL,
  `psu_usu_id` BIGINT NULL,
  `psu_pais_id` BIGINT NOT NULL,
  `psu_token` VARCHAR(500) NOT NULL,
  `psu_token_hash` CHAR(64) NOT NULL,
  `psu_plataforma` ENUM('WEB') NOT NULL DEFAULT 'WEB',
  `psu_estado` ENUM('ACTIVA','REVOCADA','INVALIDA') NOT NULL DEFAULT 'ACTIVA',
  `psu_permiso` ENUM('GRANTED','DENIED','DEFAULT') NOT NULL DEFAULT 'DEFAULT',
  `psu_navegador` VARCHAR(100) NULL,
  `psu_dispositivo` VARCHAR(100) NULL,
  `psu_sistema_operativo` VARCHAR(100) NULL,
  `psu_idioma` VARCHAR(20) NULL,
  `psu_zona_horaria` VARCHAR(64) NULL,
  `psu_user_agent` VARCHAR(500) NULL,
  `psu_ultima_actividad_en` DATETIME(6) NOT NULL,
  `psu_token_actualizado_en` DATETIME(6) NULL,
  `psu_revocado_en` DATETIME(6) NULL,
  `psu_creado_en` DATETIME(6) NOT NULL,
  `psu_actualizado_en` DATETIME(6) NOT NULL,
  PRIMARY KEY (`psu_id`),
  UNIQUE KEY `uq_psu_token_hash` (`psu_token_hash`),
  KEY `idx_psu_visitante_estado` (`psu_visitante_id`,`psu_estado`),
  KEY `idx_psu_usuario_estado` (`psu_usu_id`,`psu_estado`),
  KEY `idx_psu_pais_estado_actividad` (`psu_pais_id`,`psu_estado`,`psu_ultima_actividad_en`),
  CONSTRAINT `fk_psu_visitante` FOREIGN KEY (`psu_visitante_id`) REFERENCES `stj_visitantes` (`vis_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_psu_usuario` FOREIGN KEY (`psu_usu_id`) REFERENCES `stj_usuarios` (`usu_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_psu_pais` FOREIGN KEY (`psu_pais_id`) REFERENCES `stj_paises` (`pai_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stj_push_automatizaciones` (
  `pau_id` BIGINT NOT NULL AUTO_INCREMENT,
  `pau_codigo` VARCHAR(64) NOT NULL,
  `pau_nombre` VARCHAR(150) NOT NULL,
  `pau_descripcion` TEXT NULL,
  `pau_estado` ENUM('ACTIVA','INACTIVA') NOT NULL DEFAULT 'INACTIVA',
  `pau_paises` JSON NULL,
  `pau_retraso_minutos` INT UNSIGNED NOT NULL DEFAULT 120,
  `pau_cooldown_horas` INT UNSIGNED NOT NULL DEFAULT 24,
  `pau_maximo_por_entidad` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  `pau_titulo_plantilla` VARCHAR(160) NOT NULL,
  `pau_cuerpo_plantilla` VARCHAR(500) NOT NULL,
  `pau_action_plantilla` VARCHAR(500) NOT NULL,
  `pau_imagen` VARCHAR(500) NULL,
  `pau_configuracion` JSON NULL,
  `pau_creado_en` DATETIME(6) NOT NULL,
  `pau_actualizado_en` DATETIME(6) NOT NULL,
  PRIMARY KEY (`pau_id`),
  UNIQUE KEY `uq_pau_codigo` (`pau_codigo`),
  KEY `idx_pau_estado_codigo` (`pau_estado`,`pau_codigo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stj_push_entregas` (
  `pen_id` BIGINT NOT NULL AUTO_INCREMENT,
  `pen_automatizacion_id` BIGINT NOT NULL,
  `pen_suscripcion_id` BIGINT NULL,
  `pen_visitante_id` BIGINT NULL,
  `pen_usu_id` BIGINT NULL,
  `pen_pais_id` BIGINT NOT NULL,
  `pen_entidad_tipo` VARCHAR(50) NOT NULL,
  `pen_entidad_id` BIGINT NOT NULL,
  `pen_entidad_version` INT UNSIGNED NULL,
  `pen_stage` VARCHAR(50) NOT NULL DEFAULT 'PRIMARY',
  `pen_idempotency_key` VARCHAR(191) NOT NULL,
  `pen_titulo` VARCHAR(160) NOT NULL,
  `pen_cuerpo` VARCHAR(500) NOT NULL,
  `pen_action` VARCHAR(500) NOT NULL,
  `pen_imagen` VARCHAR(500) NULL,
  `pen_payload` JSON NULL,
  `pen_estado` ENUM('PENDIENTE','PROCESANDO','ENVIADO','REINTENTO','DESCARTADO','ERROR','CANCELADO') NOT NULL DEFAULT 'PENDIENTE',
  `pen_intentos` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `pen_programado_en` DATETIME(6) NOT NULL,
  `pen_disponible_en` DATETIME(6) NOT NULL,
  `pen_bloqueado_en` DATETIME(6) NULL,
  `pen_bloqueado_por` VARCHAR(100) NULL,
  `pen_ultimo_intento_en` DATETIME(6) NULL,
  `pen_enviado_en` DATETIME(6) NULL,
  `pen_resultado` TEXT NULL,
  `pen_error` TEXT NULL,
  `pen_creado_en` DATETIME(6) NOT NULL,
  `pen_actualizado_en` DATETIME(6) NOT NULL,
  PRIMARY KEY (`pen_id`),
  UNIQUE KEY `uq_pen_idempotency_key` (`pen_idempotency_key`),
  KEY `idx_pen_estado_disponible` (`pen_estado`,`pen_disponible_en`,`pen_programado_en`),
  KEY `idx_pen_automatizacion_estado` (`pen_automatizacion_id`,`pen_estado`),
  KEY `idx_pen_suscripcion_fecha` (`pen_suscripcion_id`,`pen_creado_en`),
  KEY `idx_pen_entidad_version` (`pen_entidad_tipo`,`pen_entidad_id`,`pen_entidad_version`),
  KEY `idx_pen_visitante_fecha` (`pen_visitante_id`,`pen_creado_en`),
  KEY `idx_pen_usuario_fecha` (`pen_usu_id`,`pen_creado_en`),
  CONSTRAINT `fk_pen_automatizacion` FOREIGN KEY (`pen_automatizacion_id`) REFERENCES `stj_push_automatizaciones` (`pau_id`),
  CONSTRAINT `fk_pen_suscripcion` FOREIGN KEY (`pen_suscripcion_id`) REFERENCES `stj_push_suscripciones` (`psu_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_pen_visitante` FOREIGN KEY (`pen_visitante_id`) REFERENCES `stj_visitantes` (`vis_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_pen_usuario` FOREIGN KEY (`pen_usu_id`) REFERENCES `stj_usuarios` (`usu_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_pen_pais` FOREIGN KEY (`pen_pais_id`) REFERENCES `stj_paises` (`pai_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stj_push_eventos` (
  `pev_id` BIGINT NOT NULL AUTO_INCREMENT,
  `pev_entrega_id` BIGINT NOT NULL,
  `pev_event_uuid` CHAR(36) NULL,
  `pev_tipo` VARCHAR(32) NOT NULL,
  `pev_origen` VARCHAR(20) NOT NULL DEFAULT 'WEB',
  `pev_datos` JSON NULL,
  `pev_ocurrido_en` DATETIME(6) NOT NULL,
  `pev_recibido_en` DATETIME(6) NOT NULL,
  PRIMARY KEY (`pev_id`),
  UNIQUE KEY `uq_pev_event_uuid` (`pev_event_uuid`),
  KEY `idx_pev_entrega_tipo_fecha` (`pev_entrega_id`,`pev_tipo`,`pev_ocurrido_en`),
  KEY `idx_pev_tipo_fecha` (`pev_tipo`,`pev_ocurrido_en`),
  CONSTRAINT `fk_pev_entrega` FOREIGN KEY (`pev_entrega_id`) REFERENCES `stj_push_entregas` (`pen_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
